os: linux
language: node_js

if: tag IS blank

stages:
  - test
  - gh pages
  - npm deploy

script: npm run test

jobs:
  include:
    - node_js: 8
    - node_js: 10
    - node_js: 12
    - node_js: 13
      after_success:
        - npm install -g codecov
        - npm run report-coverage
    - stage: gh pages
      node_js: 13
      script: skip
      before_deploy: npm run doc
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: out
        on:
          branch: master
      if: branch = master AND type = push AND fork = false
    - stage: npm deploy
      script: skip
      before_deploy: npm run build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        skip-cleanup: true
        on:
          branch: master
      if: branch = master AND type = push AND fork = false
